name: Check Link Rot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lychee (Link Checker)
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --verbose --include-mail --timeout 20 .

      - name: Upload broken links report (if any)
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: broken-links-report
          path: lychee.out
